Complete refactor.

diff --git a/bin/.local/bin/gmkpasswd b/bin/.local/bin/gmkpasswd
--- a/bin/.local/bin/gmkpasswd
+++ b/bin/.local/bin/gmkpasswd
@@ -1,26 +1,49 @@
-#!/usr/bin/env bash
+#!/bin/bash
+
+set -eu
 
 DELIM="-"
+NUM=4
+DICT="$HOME/.local/share/dict/words"
 
-function usage () {
-  echo "Usage: gmkpasswd <num> [<delim>]"
-  echo "       <num> any number > 0"
-  echo "       <delim> demlimator symbol (optional); default is '-'"
+function usage {
+  echo "Generates a password <number> words long, separated by <deliminator>."
+  echo "Usage: gmkpasswd [-h|--help] | [number] [deliminator]"
+  echo "  number:       any whole number > 0; default is 4"
+  echo "  deliminator:  ASCII deliminator; default is '-'"
 }
 
-if [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]; then
-  usage
-  exit 0
-elif [[ "$1" == "" ]] || [[ "$1" -lt 1 ]]; then
-  echo "Error: incorrect arguments"
-  usage
-  exit 1
-else
-  NUM="$1"
+function validate_arg1 {
+  if [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]; then
+    usage
+    exit 0
+  elif [[ ! "$1" =~ ^[0-9]+$ ]]; then
+    echo "Error: not a valid whole number."
+    exit 1
+  else
+    NUM="$1"
+  fi
+}
+
+function validate_arg2 {
+  if [[ "$1" == *[![:ascii:]]* ]]; then
+    echo "Error: unsupported deliminator."
+    exit 1
+  else
+    DELIM="$1"
+  fi
+}
+
+case "$#" in
+  1) validate_arg1 "$1" ;;
+  2)
+    validate_arg1 "$1"
+    validate_arg2 "$2"
+    ;;
+esac
+
+if [[ ! -e "$DICT" ]]; then
+  DICT="/usr/share/dict/words"
 fi
 
-if [[ "$2" != "" ]]; then
-  DELIM="$2"
-fi
-
-gshuf --random-source=/dev/random -n "$NUM" ~/.local/share/dict/words | tr '[:upper:]' '[:lower:]' | sed -e ':a' -e 'N' -e '$!ba' -e "s/\\n/$DELIM/g"
+gshuf --random-source=/dev/random -n "$NUM" "$DICT" | tr '[:upper:]' '[:lower:]' | sed -e ':a' -e 'N' -e '$!ba' -e "s/\\n/$DELIM/g"
