Minor cleanup work.

diff --git a/bin/.local/bin/pdf-compress b/bin/.local/bin/pdf-compress
--- a/bin/.local/bin/pdf-compress
+++ b/bin/.local/bin/pdf-compress
@@ -1,10 +1,16 @@
 #!/bin/bash
 
 set -eu
+
 COMPRESS_LEVEL="ebook"
 INPUT_FILE=""
 
-function usage {
+error() {
+  echo "Invalid option: $OPTARG" >&2
+  usage
+}
+
+usage() {
   echo "Usage: pdf-compress -h | -l [level] -f [file]"
   echo "  -l  Compression level using one of the following options:"
   echo "         screen   (screen-view-only quality, 72 dpi)"
@@ -15,23 +21,18 @@ function usage {
   echo "  -f  PDF file to compress."
 }
 
-while getopts 'hl:f:' flag; do
+while getopts ':hl:f:' flag; do
   case "${flag}" in
     h ) usage ; exit 0 ;;
     l ) COMPRESS_LEVEL="$OPTARG" ;;
     f ) INPUT_FILE="$OPTARG" ;;
-    \?) echo "Invalid option: $OPTARG" 1>&2 ; usage ; exit 1 ;;
+    \?) error ; exit 1 ;;
+    * ) error ; exit 1 ;;
   esac
 done
 
-echo
-
-if [[ "$INPUT_FILE" == "" ]]; then
-  echo "Error: Input file not specified."
-  usage
-  exit 1
-elif [[ ! -f "$INPUT_FILE" ]]; then
-  echo "Error: File does not exist, check path to file specified."
+if [[ ! -f "$INPUT_FILE" ]]; then
+  echo "Error: File does not exist, check path to file specified." >&2
   exit 1
 fi
 
@@ -48,12 +49,12 @@ if ! type gs &>/dev/null; then
 fi
 
 echo "Compressing: $INPUT_FILE"
+
 if gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/"$COMPRESS_LEVEL" -dNOPAUSE -dQUIET -dBATCH -sOutputFile="$OUTPUT_FILE" "$INPUT_FILE" &>/dev/null; then
   echo "Wrote: $OUTPUT_FILE"
 else
-  echo "Error: ghostscript error."
+  echo "Error: ghostscript error." >&2
   exit 1
 fi
 
-echo
 exit 0
