Remove redundant stow target.

diff --git a/bin/.local/bin/stow-dotfiles b/bin/.local/bin/stow-dotfiles
--- a/bin/.local/bin/stow-dotfiles
+++ b/bin/.local/bin/stow-dotfiles
@@ -74,10 +74,10 @@ git pull origin || error "Couldn't pull latest changes from origin."
 git submodule update --init --recursive || error "Problem updating submodules."
 
 # stow all packages
-_stow --restow -t "$HOME" || error "Stow returned an error."
+_stow --restow || error "Stow returned an error."
 
 # all done
-popd >/dev/null 2>&1 || error "Couldn't return to original directory."
+popd &>/dev/null || error "Couldn't return to original directory."
 
 
 if [[ "$__nc_dotfiles" -eq 0 ]]; then
