Always target home directory.

diff --git a/bin/.local/bin/stow-dotfiles b/bin/.local/bin/stow-dotfiles
--- a/bin/.local/bin/stow-dotfiles
+++ b/bin/.local/bin/stow-dotfiles
@@ -14,7 +14,7 @@ _stow() {
   for dir in */; do
     [[ ! $dir =~ ^\. ]] && __packages+=("${dir%/}")
   done
-  command stow --no-folding "$@" "${__packages[@]}"
+  command stow --no-folding --target "$HOME" "$@" "${__packages[@]}"
 }
 
 
@@ -27,6 +27,10 @@ __nc_dotfiles=1
 # set date for naming backup branch
 __date="$(date --iso-8601=seconds | tr -d ':')"
 
+# dotfile directories
+__home_dotfiles_dir="$HOME"/.dotfiles
+__nc_dotfiles_dir="$HOME"/Nextcloud/Configs/dotfiles
+
 while getopts ':be' flag; do
   case "${flag}" in
     b ) __backup=0 ;;
@@ -38,7 +42,7 @@ done
 
 
 # change directory to dotfiles
-pushd "$HOME/.dotfiles" >/dev/null 2>&1 || error "No dotfiles directory."
+pushd "$__home_dotfiles_dir" &>/dev/null || error "No dotfiles directory."
 
 # make a backup of existing dotfiles
 if [[ "$__backup" -eq 0 ]]; then
@@ -52,7 +56,7 @@ if [[ "$__backup" -eq 0 ]]; then
   git add -A || error "Could not add files to git repo."
 
   # only commit if there are changes
-  if git commit --dry-run >/dev/null 2>&1; then
+  if git commit --dry-run &>/dev/null; then
     git commit -m "Backing up dotfiles for ${__date}."
   fi
 fi
@@ -75,15 +79,17 @@ _stow --restow -t "$HOME" || error "Stow returned an error."
 # all done
 popd >/dev/null 2>&1 || error "Couldn't return to original directory."
 
+
 if [[ "$__nc_dotfiles" -eq 0 ]]; then
   # change directory to Nextcloud dotfiles
-  pushd "$HOME"/Nextcloud/Configs/dotfiles >/dev/null 2>&1 || error "No Nextcloud dotfiles directory."
+  pushd "$__nc_dotfiles_dir" &>/dev/null || error "No Nextcloud dotfiles directory."
 
   # stow all packages
   _stow --restow || error "Stow returned an error."
 
   # all done
-  popd >/dev/null 2>&1 || error "Couldn't return to original directory."
+  popd &>/dev/null || error "Couldn't return to original directory."
 fi
+
 
 exit 0
