Replace history number with user.

diff --git a/ps1/.local/bin/ps1 b/ps1/.local/bin/ps1
--- a/ps1/.local/bin/ps1
+++ b/ps1/.local/bin/ps1
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
-  # Capture the exit status from the last command
-  LAST_EXIT_STATUS="$?"
+# Capture the exit status from the last command
+LAST_EXIT_STATUS="$?"
 
 #
 # Instructions for use:
@@ -28,9 +28,9 @@ show_hostname=0
 # customize date (see `man date` for codes)
 date_format="%H:%M:%S"
 
-# show command history number (1)
-# hide command history number (0)
-show_history_num=0
+# always show username (1)
+# only show root username (0)
+show_username=0
 
 # =============================================================================
 # ANSI COLOR DEFINITIONS
@@ -45,6 +45,7 @@ bg_LightSeaGreen="\[\e[48;5;37m\]"
 bg_DarkRed="\[\e[48;5;52m\]"
 bg_SlateBlue3="\[\e[48;5;61m\]"
 bg_SteelBlue1="\[\e[48;5;75m\]"
+bg_DeepPink4="\[\e[48;5;125m\]"
 bg_DarkOrange3="\[\e[48;5;166m\]"
 bg_Grey35="\[\e[48;5;240m\]"
 bg_Grey54="\[\e[48;5;245m\]"
@@ -54,6 +55,7 @@ fg_White="\[\e[38;5;15m\]"
 fg_LightSeaGreen="\[\e[38;5;37m\]"
 fg_SlateBlue3="\[\e[38;5;61m\]"
 fg_SteelBlue1="\[\e[38;5;75m\]"
+fg_DeepPink4="\[\e[38;5;125m\]"
 fg_DarkOrange3="\[\e[38;5;166m\]"
 fg_Red1="\[\e[38;5;196m\]"
 fg_DarkOrange="\[\e[38;5;208m\]"
@@ -67,35 +69,46 @@ fg_Grey54="\[\e[38;5;245m\]"
 # SEGMENT COLORS
 # -----------------------------------------------------------------------------
 
+# Hostname segment colors
 c_hostname_bg=$bg_SlateBlue3
 c_hostname_fg=$fg_White
 c_hostname_div_fg=$fg_SlateBlue3
 
+# Date segment colors
 c_date_bg=$bg_SteelBlue1
 c_date_fg=$fg_White
 c_date_div_fg=$fg_SteelBlue1
 
-c_history_bg=$bg_DarkOrange3
-c_history_fg=$fg_White
-c_history_div_fg=$fg_DarkOrange3
+# User segment colors
+c_user_bg=$bg_DarkOrange3
+c_user_fg=$fg_White
+c_user_div_fg=$fg_DarkOrange3
+c_root_bg=$bg_DeepPink4
+c_root_fg=$fg_White
+c_root_div_fg=$fg_DeepPink4
 
+# Working directory colors
 c_cwd_bg=$bg_Grey54
 c_cwd_fg=$fg_White
 c_cwd_div_fg=$fg_Grey54
 
+# Git segment colors
 c_git_bg=$bg_Grey35
 c_gitDirty_fg=$fg_Orange1
 c_gitClean_fg=$fg_Lime
 c_git_div_fg=$fg_Grey35
 
+# Anaconda segment colors
 c_venv_bg=$bg_LightSeaGreen
 c_venv_fg=$fg_White
 c_venv_div_fg=$fg_LightSeaGreen
 
+# Suffix segment colors
 c_prompt_bg=""
 c_error_bg=$bg_DarkRed
 c_error_fg=$fg_White
 
+# Git glyph colors
 c_gitPull=$fg_SteelBlue1
 c_gitPush=$fg_LightSeaGreen
 c_gitStaged=$fg_White
@@ -287,17 +300,6 @@ build_git_prompt() {
 }
 
 
-build_history_num() {
-  local div
-
-  if [[ $show_history_num -eq 1 ]]; then
-    div="${c_history_bg}${previous_bg}${g_div}${ResetColor}"
-    histnum="${div}${c_history_bg}${c_history_fg} \! ${ResetColor}"
-    previous_bg=$c_history_div_fg
-  fi
-}
-
-
 build_hostname() {
   local div
   local c_hostname="${c_hostname_bg}${c_hostname_fg}"
@@ -308,6 +310,30 @@ build_hostname() {
     div="${c_hostname_div_fg}${previous_bg}${g_div}${ResetColor}"
     hostname="${c_hostname} \\h ${ResetColor}${div}"
     previous_bg=$c_hostname_div_fg
+  fi
+}
+
+
+build_user() {
+  local div user
+  local c_div c_user c_previous_bg
+
+  user=$(id -un)
+
+  if [[ "$user" == "root" ]]; then
+    c_div="${c_root_bg}${previous_bg}"
+    c_user="${c_root_bg}${c_root_fg}"
+    c_previous_bg=$c_root_div_fg
+  else
+    c_div="${c_user_bg}${previous_bg}"
+    c_user="${c_user_bg}${c_user_fg}"
+    c_previous_bg=$c_user_div_fg
+  fi
+
+  if [[ ( "$username" == "root" || $show_username -eq 1 ) ]]; then
+    div="${c_div}${g_div}${ResetColor}"
+    username="${div}${c_user} ${user} ${ResetColor}"
+    previous_bg=$c_previous_bg
   fi
 }
 
@@ -336,14 +362,14 @@ build_ps1() {
 
   build_hostname
   build_date
-  build_history_num
+  build_user
   build_cwd
   build_git
   build_venv
   build_exitstatus
 
   _system="${hostname}${date}"
-  _environ="${histnum}${current_dir}${ps1_git_prompt}${ps1_env_prompt}"
+  _environ="${username}${current_dir}${ps1_git_prompt}${ps1_env_prompt}"
   _shell="${exit_status}"
   _suffix="${c_prompt_bg}${previous_bg}${g_prompt}${ResetColor}"
 
